[package]
name = "fuuji/lfscripting"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
janitor = "howmanysmall/janitor@1.18.3"
promise = "evaera/promise@4.0.0"
TableUtil = "sleitnick/table-util@^1"
Timer = "sleitnick/timer@1.1.2"
FastSignal = "lucasmzreal/fastsignal@10.4.0"

[server-dependencies]